# Generated by Django 3.0.4 on 2020-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('01', 'Important'), ('02', 'Normal')], max_length=2)),
                ('complete_flag', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=99)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
